// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pryce_MVC.Data;

#nullable disable

namespace Pryce_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250321113150_AddPrimaryKeys")]
    partial class AddPrimaryKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pryce_MVC.Models.Country_Master", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("CountryMasters");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Pryce_Master_Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Module_Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Module_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SubModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubModuleId");

                    b.ToTable("MasterModules");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Pryce_Object_Module", b =>
                {
                    b.Property<int>("ObjectModule_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectModule_id"));

                    b.Property<int>("Module_id")
                        .HasColumnType("int");

                    b.Property<string>("ObjectModule_Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ObjectModule_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ObjectModule_id");

                    b.HasIndex("Module_id");

                    b.ToTable("ObjectModules");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Religion_Master", b =>
                {
                    b.Property<int>("ReligionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReligionId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ReligionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReligionId");

                    b.HasIndex("CountryId");

                    b.ToTable("ReligionMasters");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Pryce_Master_Module", b =>
                {
                    b.HasOne("Pryce_MVC.Models.Pryce_Master_Module", "ParentModule")
                        .WithMany("SubModules")
                        .HasForeignKey("SubModuleId");

                    b.Navigation("ParentModule");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Pryce_Object_Module", b =>
                {
                    b.HasOne("Pryce_MVC.Models.Pryce_Master_Module", "MasterModule")
                        .WithMany("ObjectModules")
                        .HasForeignKey("Module_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterModule");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Religion_Master", b =>
                {
                    b.HasOne("Pryce_MVC.Models.Country_Master", "Country")
                        .WithMany("Religions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Country_Master", b =>
                {
                    b.Navigation("Religions");
                });

            modelBuilder.Entity("Pryce_MVC.Models.Pryce_Master_Module", b =>
                {
                    b.Navigation("ObjectModules");

                    b.Navigation("SubModules");
                });
#pragma warning restore 612, 618
        }
    }
}
